### ISSUE TITLE
Create Layer Provider

### ISSUE THREAD

**Issue by anuraags** [nearmap/olr#57]
Create a wrapper for the open layers layer group as follows:

```
@consumer(MapCtx)
class LayerGroup {
  render() {
    <LayerGroupCtx.Provider>
      {children}
    </LayerGroupCtx.Provider>
  }
}

**Comment by nickmanks** [comment]
@anuraags https://github.com/nearmap/olr/blob/bed719fa0cebf944babe0edebfe17cab9171987a/src/layer/Group.js#L40??
